#port where service shall LISTEN for connection
listenPort: :3000

#database configuration
dbType: mysql
dbUrl: root:@tcp(127.0.0.1:3306)/golang_crud

#redis configuration
#RedisURL: 127.0.0.1:6379
redisURL: 127.0.0.1:6379

#whitelist IP
listIP:
  - 192.168.1.1
  - ::1

# logging
logsFile:
  employee: employee_logs_
  runningApp: running_app_logs_ 

logDir: "/tmp/"